;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 8/15/2010 6:34:12 PM
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0004	$	_main:
;dc_motor_keypad.c,2 :: 		void main()
;dc_motor_keypad.c,5 :: 		TRISB=0X0F;
$0004	$300F			MOVLW	15
$0005	$1303			BCF	STATUS, RP1
$0006	$1683			BSF	STATUS, RP0
$0007	$0086			MOVWF	TRISB
;dc_motor_keypad.c,6 :: 		PORTB=0XFF;
$0008	$30FF			MOVLW	255
$0009	$1283			BCF	STATUS, RP0
$000A	$0086			MOVWF	PORTB
;dc_motor_keypad.c,7 :: 		TRISC=0;
$000B	$1683			BSF	STATUS, RP0
$000C	$0187			CLRF	TRISC, 1
;dc_motor_keypad.c,11 :: 		while(1)
$000D	$	L_main_0:
;dc_motor_keypad.c,13 :: 		if(PORTB.F1)
$000D	$1283			BCF	STATUS, RP0
$000E	$1C86			BTFSS	PORTB, 1
$000F	$2812			GOTO	L_main_2
;dc_motor_keypad.c,14 :: 		{PORTC=1;
$0010	$3001			MOVLW	1
$0011	$0087			MOVWF	PORTC
;dc_motor_keypad.c,15 :: 		}
$0012	$	L_main_2:
;dc_motor_keypad.c,16 :: 		}
$0012	$280D			GOTO	L_main_0
;dc_motor_keypad.c,18 :: 		}
$0013	$2813			GOTO	$
