;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 8/8/2010 10:26:10 AM
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$004F	$	_forward_dir:
;pick_drop.c,1 :: 		void forward_dir()
;pick_drop.c,4 :: 		PORTB.F7=1; //ENABLE BIT
$004F	$1303			BCF	STATUS, RP1
$0050	$1283			BCF	STATUS, RP0
$0051	$1786			BSF	PORTB, 7
;pick_drop.c,5 :: 		PORTB.F6=1;
$0052	$1706			BSF	PORTB, 6
;pick_drop.c,6 :: 		PORTB.F5=0;
$0053	$1286			BCF	PORTB, 5
;pick_drop.c,8 :: 		PORTB.F4=1; //ENABLE BIT
$0054	$1606			BSF	PORTB, 4
;pick_drop.c,9 :: 		PORTB.F3=1;
$0055	$1586			BSF	PORTB, 3
;pick_drop.c,10 :: 		PORTB.F2=0;
$0056	$1106			BCF	PORTB, 2
;pick_drop.c,12 :: 		PORTB.F1=1;//ENABLE BIT
$0057	$1486			BSF	PORTB, 1
;pick_drop.c,13 :: 		PORTB.F0=1;
$0058	$1406			BSF	PORTB, 0
;pick_drop.c,14 :: 		PORTD.F7=0;
$0059	$1388			BCF	PORTD, 7
;pick_drop.c,16 :: 		PORTD.F4=1;//ENABLE BIT
$005A	$1608			BSF	PORTD, 4
;pick_drop.c,17 :: 		PORTD.F6=1;
$005B	$1708			BSF	PORTD, 6
;pick_drop.c,18 :: 		PORTD.F5=0;
$005C	$1288			BCF	PORTD, 5
;pick_drop.c,19 :: 		}
$005D	$0008			RETURN
$005E	$	_reverse_dir:
;pick_drop.c,20 :: 		void reverse_dir()
;pick_drop.c,23 :: 		PORTB.F7=1; //ENABLE BIT
$005E	$1303			BCF	STATUS, RP1
$005F	$1283			BCF	STATUS, RP0
$0060	$1786			BSF	PORTB, 7
;pick_drop.c,24 :: 		PORTB.F6=0;
$0061	$1306			BCF	PORTB, 6
;pick_drop.c,25 :: 		PORTB.F5=1;
$0062	$1686			BSF	PORTB, 5
;pick_drop.c,27 :: 		PORTB.F4=1; //ENABLE BIT
$0063	$1606			BSF	PORTB, 4
;pick_drop.c,28 :: 		PORTB.F3=0;
$0064	$1186			BCF	PORTB, 3
;pick_drop.c,29 :: 		PORTB.F2=1;
$0065	$1506			BSF	PORTB, 2
;pick_drop.c,31 :: 		PORTB.F1=1;//ENABLE BIT
$0066	$1486			BSF	PORTB, 1
;pick_drop.c,32 :: 		PORTB.F0=0;
$0067	$1006			BCF	PORTB, 0
;pick_drop.c,33 :: 		PORTD.F7=1;
$0068	$1788			BSF	PORTD, 7
;pick_drop.c,35 :: 		PORTD.F4=1;//ENABLE BIT
$0069	$1608			BSF	PORTD, 4
;pick_drop.c,36 :: 		PORTD.F6=0;
$006A	$1308			BCF	PORTD, 6
;pick_drop.c,37 :: 		PORTD.F5=1;
$006B	$1688			BSF	PORTD, 5
;pick_drop.c,38 :: 		}
$006C	$0008			RETURN
$0004	$	_main:
;pick_drop.c,42 :: 		void main()
;pick_drop.c,44 :: 		TRISB=0;
$0004	$1303			BCF	STATUS, RP1
$0005	$1683			BSF	STATUS, RP0
$0006	$0186			CLRF	TRISB, 1
;pick_drop.c,45 :: 		TRISD=0;
$0007	$0188			CLRF	TRISD, 1
;pick_drop.c,46 :: 		PORTD=0;
$0008	$1283			BCF	STATUS, RP0
$0009	$0188			CLRF	PORTD, 1
;pick_drop.c,47 :: 		PORTB=0;
$000A	$0186			CLRF	PORTB, 1
;pick_drop.c,48 :: 		while(1)
$000B	$	L_main_0:
;pick_drop.c,50 :: 		forward_dir();
$000B	$204F			CALL	_forward_dir
;pick_drop.c,51 :: 		delay_ms(40000);
$000C	$30CC			MOVLW	204
$000D	$00FC			MOVWF	STACK_12
$000E	$30FF			MOVLW	255
$000F	$00FB			MOVWF	STACK_11
$0010	$30FF			MOVLW	255
$0011	$00FA			MOVWF	STACK_10
$0012	$0BFC			DECFSZ	STACK_12, F
$0013	$2815			GOTO	$+2
$0014	$281C			GOTO	$+8
$0015	$0BFB			DECFSZ	STACK_11, F
$0016	$2818			GOTO	$+2
$0017	$281B			GOTO	$+4
$0018	$0BFA			DECFSZ	STACK_10, F
$0019	$2818			GOTO	$-1
$001A	$2815			GOTO	$-5
$001B	$2812			GOTO	$-9
$001C	$30F9			MOVLW	249
$001D	$00FB			MOVWF	STACK_11
$001E	$30FF			MOVLW	255
$001F	$00FA			MOVWF	STACK_10
$0020	$0BFB			DECFSZ	STACK_11, F
$0021	$2823			GOTO	$+2
$0022	$2826			GOTO	$+4
$0023	$0BFA			DECFSZ	STACK_10, F
$0024	$2823			GOTO	$-1
$0025	$2820			GOTO	$-5
$0026	$30D4			MOVLW	212
$0027	$00FA			MOVWF	STACK_10
$0028	$0BFA			DECFSZ	STACK_10, F
$0029	$2828			GOTO	$-1
$002A	$0000			NOP
$002B	$0000			NOP
;pick_drop.c,52 :: 		reverse_dir();
$002C	$205E			CALL	_reverse_dir
;pick_drop.c,53 :: 		delay_ms(40000);
$002D	$30CC			MOVLW	204
$002E	$00FC			MOVWF	STACK_12
$002F	$30FF			MOVLW	255
$0030	$00FB			MOVWF	STACK_11
$0031	$30FF			MOVLW	255
$0032	$00FA			MOVWF	STACK_10
$0033	$0BFC			DECFSZ	STACK_12, F
$0034	$2836			GOTO	$+2
$0035	$283D			GOTO	$+8
$0036	$0BFB			DECFSZ	STACK_11, F
$0037	$2839			GOTO	$+2
$0038	$283C			GOTO	$+4
$0039	$0BFA			DECFSZ	STACK_10, F
$003A	$2839			GOTO	$-1
$003B	$2836			GOTO	$-5
$003C	$2833			GOTO	$-9
$003D	$30F9			MOVLW	249
$003E	$00FB			MOVWF	STACK_11
$003F	$30FF			MOVLW	255
$0040	$00FA			MOVWF	STACK_10
$0041	$0BFB			DECFSZ	STACK_11, F
$0042	$2844			GOTO	$+2
$0043	$2847			GOTO	$+4
$0044	$0BFA			DECFSZ	STACK_10, F
$0045	$2844			GOTO	$-1
$0046	$2841			GOTO	$-5
$0047	$30D4			MOVLW	212
$0048	$00FA			MOVWF	STACK_10
$0049	$0BFA			DECFSZ	STACK_10, F
$004A	$2849			GOTO	$-1
$004B	$0000			NOP
$004C	$0000			NOP
;pick_drop.c,54 :: 		}
$004D	$280B			GOTO	L_main_0
;pick_drop.c,55 :: 		}
$004E	$284E			GOTO	$
