;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 9/2/2010 10:50:52 PM
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0004	$	_main:
;servo_init.c,2 :: 		void main()
;servo_init.c,5 :: 		trisb=0x00;
$0004	$1303			BCF	STATUS, RP1
$0005	$1683			BSF	STATUS, RP0
$0006	$0186			CLRF	TRISB, 1
;servo_init.c,6 :: 		while(1)
$0007	$	L_main_0:
;servo_init.c,8 :: 		for(i=0;i<100;i++)
$0007	$1283			BCF	STATUS, RP0
$0008	$01A0			CLRF	main_i_L0
$0009	$01A1			CLRF	main_i_L0+1
$000A	$	L_main_2:
$000A	$3000			MOVLW	0
$000B	$0221			SUBWF	main_i_L0+1, 0
$000C	$1D03			BTFSS	STATUS, Z
$000D	$2810			GOTO	L_main_5
$000E	$3064			MOVLW	100
$000F	$0220			SUBWF	main_i_L0, 0
$0010	$	L_main_5:
$0010	$1803			BTFSC	STATUS, C
$0011	$2837			GOTO	L_main_3
;servo_init.c,10 :: 		portb= 0xff;
$0012	$30FF			MOVLW	255
$0013	$0086			MOVWF	PORTB
;servo_init.c,11 :: 		delay_us(1500);
$0014	$3002			MOVLW	2
$0015	$00FB			MOVWF	STACK_11
$0016	$30FF			MOVLW	255
$0017	$00FA			MOVWF	STACK_10
$0018	$0BFB			DECFSZ	STACK_11, F
$0019	$281B			GOTO	$+2
$001A	$281E			GOTO	$+4
$001B	$0BFA			DECFSZ	STACK_10, F
$001C	$281B			GOTO	$-1
$001D	$2818			GOTO	$-5
$001E	$30F0			MOVLW	240
$001F	$00FA			MOVWF	STACK_10
$0020	$0BFA			DECFSZ	STACK_10, F
$0021	$2820			GOTO	$-1
$0022	$0000			NOP
$0023	$0000			NOP
;servo_init.c,12 :: 		portb= 0x00;
$0024	$0186			CLRF	PORTB, 1
;servo_init.c,13 :: 		delay_us(18500);
$0025	$3018			MOVLW	24
$0026	$00FB			MOVWF	STACK_11
$0027	$30FF			MOVLW	255
$0028	$00FA			MOVWF	STACK_10
$0029	$0BFB			DECFSZ	STACK_11, F
$002A	$282C			GOTO	$+2
$002B	$282F			GOTO	$+4
$002C	$0BFA			DECFSZ	STACK_10, F
$002D	$282C			GOTO	$-1
$002E	$2829			GOTO	$-5
$002F	$30F6			MOVLW	246
$0030	$00FA			MOVWF	STACK_10
$0031	$0BFA			DECFSZ	STACK_10, F
$0032	$2831			GOTO	$-1
;servo_init.c,14 :: 		}
$0033	$	L_main_4:
;servo_init.c,8 :: 		for(i=0;i<100;i++)
$0033	$0AA0			INCF	main_i_L0, 1
$0034	$1903			BTFSC	STATUS, Z
$0035	$0AA1			INCF	main_i_L0+1, 1
;servo_init.c,14 :: 		}
$0036	$280A			GOTO	L_main_2
$0037	$	L_main_3:
;servo_init.c,15 :: 		}
$0037	$2807			GOTO	L_main_0
;servo_init.c,16 :: 		}
$0038	$2838			GOTO	$
